server:
  port: 7979
  max-http-header-size: 102400
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 102400

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@

swagger:
  title: @pom.artifactId@
  description: @pom.description@